name: weather_project
version: '1.0.0'
profile: weather_project

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  weather_project:
    # 1. Weather Domain Configuration
    weather:
      +schema: weather  # Creates schema: <target>_weather
      staging:
        +materialized: view
      mart:
        +materialized: table

    # 2. Crypto Domain Configuration
    crypto:
      +schema: crypto   # Creates schema: <target>_crypto
      staging:
        +materialized: view
      marts:
        +materialized: table
