name: Deploy to Production (Self-Hosted)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # 1. RUNNER SELECTION: Tell GitHub to use YOUR server, not their cloud
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Update Project Code
      run: |
        # 2. SYNC FILES: Copy from the Runner's folder to your Project folder
        # We exclude .git and the runner itself to prevent loops
        rsync -av --exclude='.git' --exclude='actions-runner' ./ /home/ubuntu/weather-data-pipeline/

    - name: Update Airflow DAGs
      run: |
        # 3. UPDATE DAG: Copy the DAG file to where Airflow reads it
        cp /home/ubuntu/weather-data-pipeline/airflow/dags/weather_dag.py /home/ubuntu/airflow/dags/

    - name: Install Requirements
      run: |
        # 4. DEPENDENCIES: Activate venv and install
        source /home/ubuntu/airflow_env/bin/activate
        pip install -r /home/ubuntu/weather-data-pipeline/requirements.txt
        
    - name: Notify
      run: echo "🚀 Deployment Completed on EC2 Private Runner!"